namespace: 'sojo-travel-dev'
platform:
  global:
    apiVersion: ambassador/v1
    kind: Mapping
    host: ".*.axonvibelabs.com"
    host_regex: true
    add_response_headers:
      strict-transport-security: "max-age=300; includeSubDomains"
      x-clacks-overhead: GNU Terry Pratchett
      x-test-proto: "%PROTOCOL%"
      x-test-ip: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
  services:
    aaa:
      name: aaa-sojo-travel-dev
      prefix: "/sojo-travel/dev/aaa/"
      service: http://aaa.sojo-travel-dev.svc:8080
    agent:
      name: agent-sojo-travel-dev
      prefix: "/sojo-travel/dev/agent/"
      service: http://agent.sojo-travel-dev.svc:8080
    bookmark:
      name: bookmark-sojo-travel-dev
      prefix: "/sojo-travel/dev/bookmark/"
      service: http://bookmark.sojo-travel-dev.svc:8080
    capture:
      name: capture-sojo-travel-dev
      prefix: "/sojo-travel/dev/capture/"
      service: http://capture.sojo-travel-dev.svc:8080
    fact:
      name: fact-sojo-travel-dev
      prefix: "/sojo-travel/dev/fact/"
      service: http://fact.sojo-travel-dev.svc:8080
    notification:
      name: notification-sojo-travel-dev
      prefix: "/sojo-travel/dev/notification/"
      service: http://notification.sojo-travel-dev.svc:8080
    sensing-receiver-service:
      name: sensing-sojo-travel-dev
      regex_prefix: true
      prefix: "/sojo-travel/dev/(sensing|timeline)?/"
      service: http://sensing-receiver-service.sojo-travel-dev.svc:8080
    profile:
      name: profile-sojo-travel-dev
      prefix: "/sojo-travel/dev/profile/"
      service: http://profile.sojo-travel-dev.svc:8080
    vehicle:
      name: vehicle-sojo-travel-dev
      prefix: "/sojo-travel/dev/vehicle/"
      service: http://vehicle.sojo-travel-dev.svc:8080
    transit-route-shape:
      name: transit-sojo-travel-dev
      prefix: "/sojo-travel/dev/transit-route-shape/"
      service: http://transit-route-shape.sojo-travel-dev.svc:8080
    routing:
      name: routing-sojo-travel-dev
      prefix: "/sojo-travel/dev/routing/"
      service: http://routing.sojo-travel-dev.svc:8080
    sensorsim:
      name: sensorsim-sojo-travel-dev
      prefix: "/sojo-travel/dev/sensorsim/"
      service: http://sensorsim.sojo-travel-dev.svc:8080
    metrics:
      name: metrics-sojo-travel-dev
      prefix: "/sojo-travel/dev/metrics/"
      service: http://metrics.sojo-travel-dev.svc:8080
    user-dashboard-api:
      name: user-dashboard-api-sojo-travel-dev
      prefix: "/sojo-travel/dev/user-dashboard-api/"
      service: http://user-dashboard-api.sojo-travel-dev.svc:8080
